# Bot Configuration
bot:
  version: "2.0.0"
  debug_mode: true
  application_id: ${APPLICATION_ID}
  guild_id: ${GUILD_ID}
  admin_role_id: ${ADMIN_ROLE_ID}
  admin_user_id: ${ADMIN_USER_ID}
  news_role_id: ${NEWS_ROLE_ID}

# Channel Configuration
channels:
  news: ${NEWS_CHANNEL_ID}
  errors: ${ERRORS_CHANNEL_ID}
  logs: ${LOG_CHANNEL_ID}

# API Tokens (from environment variables)
tokens:
  discord: ${DISCORD_TOKEN}

# Auto-posting Configuration
auto_post:
  min_interval_hours: 1
  max_interval_hours: 24
  default_interval_hours: 6

# Resource Monitoring
monitoring:
  metrics:
    port: 8000
    collection_interval: 60
  resource_alerts:
    cpu_threshold: 80.0  # percentage
    ram_threshold: 70.0  # percentage
    check_interval: 30  # seconds

# Rich Presence
rich_presence:
  update_interval: 60  # seconds
  posted_duration: 600  # seconds

# Logging
logging:
  file: "logs/NewsBot.log"
  max_lines_tail: 15
  heartbeat_interval: 3600  # seconds

# Circuit Breaker
circuit_breaker:
  failure_threshold: 5
  reset_timeout: 300  # seconds
  half_open_timeout: 60  # seconds

# Cache
cache:
  redis:
    host: "localhost"
    port: 6379
    db: 0

# Telegram configuration
telegram:
  api_id: ${TELEGRAM_API_ID}
  api_hash: ${TELEGRAM_API_HASH}
  token: ${TELEGRAM_TOKEN} 