automation:
  enabled: true
  interval_minutes: 60
  max_posts_per_session: 1
  min_content_length: 50
  notify_on_errors: true
  notify_on_success: false
  require_media: false
  require_text: true
  silent_mode: false
  startup_delay_minutes: 2
  use_ai_filtering: true
bot:
  admin_role_id: 1228455909827805311
  admin_user_id: 259725211664908288
  application_id: 1378540050006147114
  debug_mode: true
  guild_id: 1228455909827805308
  news_role_id: 1312489916764131390
  version: 4.5.0
channels:
  active:
  - moraselalthawrah
  - jh_team
  - shaamnetwork
  - alktroone
  - alhourya_news
  - alekhbariahsy
  - samsyria01
  blacklisted_posts:
  - 168013
  - 168050
  - 168066
  - 168065
  - 168163
  - 169334
  - 11445
  - 11452
  - 77934
  - 169442
  - 1091
  - 1092
  channel_metadata:
    alekhbariahsy:
      date_added: '2025-06-10T22:04:16.738556'
      date_deactivated: null
      status: activated
    alhourya_news:
      date_added: '2025-06-10T22:03:30.383424'
      date_deactivated: null
      status: activated
    alktroone:
      date_added: '2025-06-10T22:01:32.494153'
      date_deactivated: null
      status: activated
    jh_team:
      date_added: '2025-06-10T22:00:16.211827'
      date_deactivated: null
      status: activated
    moraselalthawrah:
      date_added: '2025-06-10T16:08:19.691136'
      date_deactivated: null
      status: activated
    samsyria01:
      date_added: '2025-06-22T20:29:23.544967'
      date_deactivated: null
      status: activated
    shaamnetwork:
      date_added: '2025-06-10T22:00:49.279866'
      date_deactivated: null
      status: activated
    symoigov:
      date_added: '2025-06-10T22:02:12.750373'
      date_deactivated: '2025-06-10T22:03:02.813444'
      status: deactivated
    test_add_channel_demo:
      date_added: '2025-06-22T19:57:02.656413'
      date_deactivated: '2025-06-22T19:57:02.660977'
      status: deactivated
    test_channel:
      date_added: '2025-06-22T04:01:36.047120'
      date_deactivated: '2025-06-22T20:21:46.018542'
      status: deactivated
    test_new_channel:
      date_added: '2025-06-22T19:56:20.130223'
      date_deactivated: '2025-06-22T19:56:20.131397'
      status: deactivated
discord:
  channels:
    errors: 1378781937279176774
    logs: 1378553893083938957
    news: 1382112473423020062
  guild_id: 1228455909827805308
  token: YOUR_DISCORD_TOKEN_HERE
environments:
  development:
    automation:
      interval_minutes: 180
    bot:
      debug_mode: true
    monitoring:
      log_level: DEBUG
      resource_alerts:
        enabled: false
        cpu_threshold: 95.0
        ram_threshold: 90.0
        check_interval: 300
        reason: "Development environment - CPU spikes are normal during testing"
  production:
    automation:
      interval_minutes: 180
    bot:
      debug_mode: false
    monitoring:
      log_level: INFO
      resource_alerts:
        enabled: true
        cpu_threshold: 80.0
        ram_threshold: 75.0
        check_interval: 120
        reason: "Production VPS monitoring - alert on sustained high usage"
features:
  ai_categorization: true
  ai_translation: true
  auto_posting: true
  forum_tags: true
  health_monitoring: true
  location_detection: true
  news_role_pinging: true
  rich_presence: true
meta:
  created: '2025-06-23T12:08:43.254900'
  description: Unified NewsBot Configuration
  last_updated: '2025-06-24T14:41:51.430870'
  version: 1.0.0
monitoring:
  health_checks: true
  log_level: INFO
  log_retention_days: 30
  max_log_size_mb: 50
  performance_tracking: true
  resource_alerts:
    enabled: true
    cpu_threshold: 85.0
    ram_threshold: 80.0
    check_interval: 120
    reason: "Default resource monitoring"
openai:
  api_key: YOUR_OPENAI_API_KEY_HERE
  max_tokens: 4000
  model: gpt-3.5-turbo
telegram:
  api_hash: f5f83a4c91b0f2f202ed3c730c3f7ef3
  api_id: 23834972
  phone_number: '+1234567890'
  token: ''
test:
  e2e:
    timestamp: '2025-06-24T14:05:56.407725'
  integration:
    timestamp: '2025-06-24T15:29:18.045702'

# Advanced AI Content Analysis Configuration
advanced_ai:
  # Content analysis settings
  content_analysis:
    enabled: true
    cache_ttl_seconds: 3600  # 1 hour cache for analysis results
    parallel_analysis: true  # Run all AI analyses in parallel
    
    # Analysis thresholds
    thresholds:
      high_credibility: 0.7
      low_credibility: 0.4
      high_viral_potential: 0.7
      low_viral_potential: 0.3
      high_emotional_intensity: 0.7
      low_emotional_intensity: 0.3
      high_manipulation_risk: 0.6
      cultural_sensitivity_threshold: 0.5
      
  # Emotional analysis configuration
  emotional_analysis:
    enabled: true
    dimensions:
      - anger
      - fear
      - hope
      - sadness
      - joy
      - urgency
      - anxiety
      - determination
    fallback_emotion: "urgency"
    
  # Credibility assessment configuration
  credibility_assessment:
    enabled: true
    factors:
      - source_reliability
      - fact_checkable
      - bias_level
      - emotional_manipulation
      - evidence_quality
      - language_quality
    warning_threshold: 2  # Number of warnings before flagging
    
  # Viral potential prediction
  viral_prediction:
    enabled: true
    engagement_metrics:
      - likes
      - shares
      - comments
    timing_optimization: true
    
  # Cultural context analysis
  cultural_analysis:
    enabled: true
    target_cultures:
      - syrian
      - arabic
      - middle_eastern
    sensitivity_check: true
    localization_suggestions: true
    
  # Content optimization
  optimization:
    enabled: true
    categories:
      - emotional_optimization
      - credibility_enhancement
      - viral_potential_boost
      - cultural_adaptation
      - timing_optimization
      - engagement_strategies
    max_recommendations_per_category: 3
    
  # Performance settings
  performance:
    max_content_length: 2000  # Characters to analyze
    timeout_seconds: 30
    retry_attempts: 2
    concurrent_analyses: 4
    
  # OpenAI API settings for advanced analysis
  openai:
    model: "gpt-4-turbo-preview"
    temperature:
      emotional_analysis: 0.3
      credibility_assessment: 0.2
      viral_prediction: 0.4
      cultural_analysis: 0.3
    max_tokens:
      emotional_analysis: 500
      credibility_assessment: 600
      viral_prediction: 400
      cultural_analysis: 500
      
  # Report generation
  reports:
    enabled: true
    include_confidence_scores: true
    include_processing_times: true
    include_recommendations: true
    max_report_length: 4000
    chunk_size: 1900  # For Discord message splitting
