name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          pip install -r requirements-dev.txt
          pytest --cov=src --cov-report=term-missing
          
      - name: Generate changelog
        id: changelog
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          
          # Generate changelog from git commits
          CHANGELOG=$(git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD)
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: NewsBot v${{ steps.changelog.outputs.VERSION }}
          body: |
            ## What's Changed
            
            ${{ steps.changelog.outputs.CHANGELOG }}
            
            ## Installation
            
            ```bash
            git clone https://github.com/${{ github.repository }}.git
            cd NewsBot
            pip install -r requirements.txt
            cp env.example .env
            # Edit .env with your credentials
            python run.py
            ```
            
            ## Docker
            
            ```bash
            docker pull ghcr.io/${{ github.repository }}:v${{ steps.changelog.outputs.VERSION }}
            ```
            
            **Full Changelog**: https://github.com/${{ github.repository }}/compare/v${{ steps.changelog.outputs.VERSION }}...HEAD
          draft: false
          prerelease: false 